---
abstract: 'Make Moose sub classes with non required attributes.'
author:
  - 'Colin Newell, C<< <colin.newell at gmail.com> >>'
  - 'Colin Newell <colin.newell@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-NotRequired
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
  perl: 5.6.0
resources:
  homepage: https://github.com/colinnewell/MooseX-NotRequired
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/colinnewell/MooseX-NotRequired.git
    web: https://github.com/colinnewell/MooseX-NotRequired
version: 0.09
